# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81befa1f10a86cc2728e4e6eac5302604422059bca46f578083e36c4455f27becc015c66e5261bba2e2b13f5d1e4052d521135099efe4bbf62bf1c3b96468b2a

test:
  secret_key_base: 8ea0cd9fda90efa2a0f8dc210e6b993dddb017824aa94e490f7ce255d94960ae4b458e67642ee6eb44c8eb127cb12b5b09a5f74f5e502fd9f24f0aef3fe3d028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
